### ISSUE TITLE
[Nitpick] Song metadata should be cleared when current selection is not a song

### ISSUE THREAD

**Issue by Joehuu** [TeamRizu/OutFox#394]
![image](https://user-images.githubusercontent.com/35318437/129113575-adfea6b8-20ba-4b37-9a5f-9c4191dec2be.png)

**Give an example of what is wrong**

The red areas are not cleared when a song is not selected (e.g. pack headers, random, roulette).

**Given an example of what it should look like**

It should clear like the green areas with 0's or N/A.

**Comment by Sudospective** [comment]
I think this is due to a missing message command. There is a check for the current artist, genre, NPS, etc. when the chart is switch, which happens when you select a different song. This doesn't happen when the song is switched to a folder, though. I fixed this in my own theme by adding a `CurrentSongChanged` message command, but I'm sure there's a better way to go about it, and it's possible that this may need to be looked at on the engine side. Maybe right now rather than checking if the steps have changed before sending a message, it checks if new steps are loaded, which doesn't include no steps.

**Comment by JoseVarelaP** [comment]
Dealt this problem alongside @ListenerJubatus, for the next release.

**Comment by Joehuu** [comment]
NPS graph is still not cleared.

<img width="574" alt="Screen Shot 2021-08-22 at 12 43 21 PM" src="https://user-images.githubusercontent.com/35318437/130368016-e027040b-1599-4d7e-8686-084d050dd909.png">

**Comment by Joehuu** [comment]
Bumping as my last comment hasn't been resolved (note that I can't reopen this myself).

**Comment by JoseVarelaP** [comment]
What area is still not clearing correctly?

**Comment by Joehuu** [comment]
When changing to a non-song before NPS is shown, high score section is not cleared (still has grade and "skill" graphs).

When changing after NPS is shown, the NPS graph is not cleared.

https://user-images.githubusercontent.com/35318437/131204673-46eda999-11a4-4617-b3ab-8ed75d178c73.mov
